### ISSUE TITLE
Generic type 'Type<T>' requires 1 type argument(s) 

### ISSUE THREAD

**Issue by pratikthecook** [iurii-kyrylenko/angular2-webpack#1]
Hi,
I currently require to build a RC5 app with lazy loading support. As of now i cannot move to GA. I found ur awesome started project with everything configured.
i did npm install -> npm postinstall - npm run and encounterd the following error

ERROR in ./src/app/utils/async-ng-module-loader.ts
(12,18): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

ERROR in /home/pratik/Desktop/ng2build/October Build/ng2-RC5-MDB/src/app/app.component.spec.ts
(2,3): error TS2305: Module '"/home/pratik/Desktop/ng2build/October Build/ng2-RC5-MDB/node_modules/@angular/core/testing/index"' has no exported member 'addProviders'.

Following is my package.json (untouched)

```
{
  "name": "angular2-webpack",
  "version": "1.0.0",
  "description": "A webpack starter for angular 2",
  "scripts": {
    "start": "webpack-dev-server --inline --progress --port 8081",
    "test": "karma start",
    "test-watch": "karma start --single-run false --auto-watch true",
    "build": "rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail",
    "postinstall": "typings install"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/common": "^2.0.0-rc.5",
    "@angular/compiler": "^2.0.0-rc.5",
    "@angular/core": "^2.0.0-rc.5",
    "@angular/forms": "^0.3.0",
    "@angular/http": "^2.0.0-rc.5",
    "@angular/platform-browser": "^2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.5",
    "@angular/router": "^3.0.0-rc.1",
    "core-js": "^2.4.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "angular2-template-loader": "^0.4.0",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-jasmine": "^0.3.8",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "style-loader": "^0.13.1",
    "ts-loader": "^0.8.1",
    "typescript": "^1.8.10",
    "typings": "^1.0.4",
    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0"
  }
}

```

I dont know whats going wrong could you please post a solution for this. Thanks

**Comment by iurii-kyrylenko** [comment]
Thanks, @pratikthecook for finding the issue.

The problem is in semversions of angular modules. Angular 2 has gone significantly ahead from rc5. If you still use the rc5, the versions of all `@angular/xxx` should match exactly: the caret `^` symbol should be removed. I created a special branch `rc5`. Please, look into [changes](https://github.com/iurii-kyrylenko/angular2-webpack/commit/154fc12780287436bddb40fa6352ab888e889f3a).

**Comment by iurii-kyrylenko** [comment]
@pratikthecook: After fixing `package.json`, reinstall dependencies: `npm i`

**Comment by pratikthecook** [comment]
Awesome and thanks a lot again....it works!
